-- DROPPING VIEW "[VIEW_STAGING_LEDGER_JNL_LINE]"
--drop view [finance_landing].[VIEW_STAGING_LEDGER_JNL_LINE];
create schema FINANCE_STAGING;

CREATE VIEW FINANCE_STAGING.VIEW_GL_LEDGER_COMB_TRANS
AS
SELECT *
FROM
(
SELECT DISTINCT
	CONVERT(INT, CONVERT(datetime, G.ACCT_DATE, 112)) AS DATE_ID,
	L.DATA_AREA_ID, 
	G.COMPANY,
	M.ROW_ID as MAIN_ACCT_ROWID,
	M.ACCT_ID,  
	G.BRANCH_ID,
	G.DEPT_ID,
	G.EMP_ID,
	G.LEGAL_ENTITY_ID,
	G.XELM_LEGAL_ENTITY_ID,
	G.PROJ_ID,
	G.TASK_ID,
	G.TAX_ID,
	M.ACCT_CAT,
	M.ACCT_NAME,
	M.ACCT_CAT_DESC,
	M.[ACCT_SUB_CAT_DESC_1],
	M.[ACCT_SUB_CAT_DESC_2],
	M.[ACCT_SUB_CAT_DESC_3],
	M.[ACCT_SUB_CAT_DESC_4],
	L.JNL_BATCH_NBR,
	L.VOUCHER,
	G.JNL_NBR, 
	H.JNL_NAME, 
	G.JNL_DESC, --check if you need both 
	H.[JNL_DESC] AS LEDGER_JNL_DESC, --check if you need both 
	G.LEDGER_NAME, 
	G.LEDGER_ACCT, 
	G.DOC_NBR AS DOC_DESC, 
	H.SRC_CREATE_BY,
	H.SRC_UPD_BY,
	G.TRAN_CURR_CODE,
	SUM(ISNULL(G.TRAN_CURR_DR_AMT,0)) AS TRAN_CURR_DR_AMT, 
	SUM(ISNULL(G.TRANS_CURR_CR_AMT,0)) AS TRANS_CURR_CR_AMT,
	SUM(ISNULL(G.ACCT_CURR_AMT,0)) AS ACCT_CURR_AMT,
	SUM(ISNULL(G.RPT_CURR_AMT,0)) AS RPT_CURR_AMT,
	SUM(ISNULL(G.TRAN_CURR_AMT,0))  AS TRAN_CURR_AMT,
	SUM(ISNULL(H.JNL_TOTAL_CR,0)) AS JNL_TOTAL_CR, 
	SUM(ISNULL(H.JNL_TOTAL_DR,0)) AS JNL_TOTAL_DR
from [FINANCE].[GEN_JNL_ACCT_ENTITY_ENTRY] G
	INNER JOIN [FINANCE].MAIN_ACCT M  ON M.ROW_ID = G.MAIN_ACCT_ROW_ID
	LEFT JOIN [FINANCE].LEDGER_JNL_LINE L ON G.VOUCHER = L.VOUCHER and L.MAIN_ACCT_ROW_ID=G.MAIN_ACCT_ROW_ID
	LEFT JOIN [FINANCE].[LEDGER_JNL_HEADER] H ON H.JNL_BATCH_NBR = L.JNL_BATCH_NBR
GROUP BY
	CONVERT(INT, CONVERT(datetime, G.ACCT_DATE, 112)),
	L.DATA_AREA_ID, 
	G.COMPANY,
	M.ROW_ID,
	M.ACCT_ID,  
	G.BRANCH_ID,
	G.DEPT_ID,
	G.EMP_ID,
	G.LEGAL_ENTITY_ID,
	G.XELM_LEGAL_ENTITY_ID,
	G.PROJ_ID,
	G.TASK_ID,
	G.TAX_ID,
	M.ACCT_CAT,
	M.ACCT_NAME,
	M.ACCT_CAT_DESC,
	M.[ACCT_SUB_CAT_DESC_1],
	M.[ACCT_SUB_CAT_DESC_2],
	M.[ACCT_SUB_CAT_DESC_3],
	M.[ACCT_SUB_CAT_DESC_4],
	L.JNL_BATCH_NBR,
	L.VOUCHER,
	G.JNL_NBR, 
	H.JNL_NAME, 
	G.JNL_DESC,
	H.[JNL_DESC],
	G.LEDGER_NAME, 
	G.LEDGER_ACCT, 
	G.DOC_NBR, 
	H.SRC_CREATE_BY,
	H.SRC_UPD_BY,
	G.TRAN_CURR_CODE
)A