--CREATE VIEW [COMMWEB].[VIEW_SECURITY_CLASS_CODES]
--AS
with TempReportLegend as 
(
-- Commission Details report legend:
SELECT 11 as Label_Id, 'en' as User_Language, 'Security Type Legend' as Security_Class_Description
UNION ALL
SELECT 11, 'fr', 'Légende type titre'
UNION ALL
SELECT 12, 'en', 'Security Class Legend'
UNION ALL
SELECT 12, 'fr', 'Légende cat. titre'
UNION ALL
SELECT 13, 'en', 'Type'
UNION ALL
SELECT 13, 'fr', 'Type'
UNION ALL
SELECT 14, 'en', 'Description'
UNION ALL
SELECT 14, 'fr', 'Description'
UNION ALL
SELECT 15, 'en', 'Class'
UNION ALL
SELECT 15, 'fr', 'Cat.'
UNION ALL
SELECT 16, 'en', 'Description'
UNION ALL
SELECT 16, 'fr', 'Description'

UNION ALL
SELECT 21, 'en', 'Bond'
UNION ALL
SELECT 21, 'fr', 'Obligation'
UNION ALL
SELECT 22, 'en', 'Equity'
UNION ALL
SELECT 22, 'fr', 'Action'
UNION ALL
SELECT 23, 'en', 'Mutual Fund'
UNION ALL
SELECT 23, 'fr', 'Fonds commun de placement'
UNION ALL
SELECT 24, 'en', 'Option'
UNION ALL
SELECT 24, 'fr', 'Option'
UNION ALL
SELECT 25, 'en', 'ASSET BACKED'
UNION ALL
SELECT 25, 'fr', 'TACM'
UNION ALL
SELECT 26, 'en', 'MARKET BONDS'
UNION ALL
SELECT 26, 'fr', 'OBLIG. NÉGOCIABLES'
UNION ALL
SELECT 27, 'en', 'MKT BONDS – PROV SVGS BOND'
UNION ALL
SELECT 27, 'fr', 'OBLIG. NÉGOCIABLES – OBLIG. D’ÉPARGNE PROV.'
UNION ALL
SELECT 28, 'en', 'COMMON SHARES'
UNION ALL
SELECT 28, 'fr', 'ACTIONS ORDINAIRES'
UNION ALL
SELECT 29, 'en', 'LEGENDED AND RESTRICTED SHARES'
UNION ALL
SELECT 29, 'fr', 'ACTIONS SUBALTERNES ET AVEC REST. DE TRANSFERT'
UNION ALL
SELECT 30, 'en', 'STRIPPED INSTRUMENT – COUPON'
UNION ALL
SELECT 30, 'fr', 'INSTRUMENT DÉMÉMBRÉ – COUPON'
UNION ALL
SELECT 31, 'en', 'STRIPPED INSTRUMENT – PRINCIPAL'
UNION ALL
SELECT 31, 'fr', 'INSTRUMENT DÉMÉMBRÉ – CAPITAL'
UNION ALL
SELECT 32, 'en', 'STRIPPED INSTRUMENT –  SENTINELS'
UNION ALL
SELECT 32, 'fr', 'INSTRUMENT DÉMÉMBRÉ – SENTINELS'
UNION ALL
SELECT 33, 'en', 'STRIPPED INSTRUMENT – TIGRS'
UNION ALL
SELECT 33, 'fr', 'INSTRUMENT DÉMEMBRÉ – TIGRS'
UNION ALL
SELECT 34, 'en', 'MONTHLY INCOME'
UNION ALL
SELECT 34, 'fr', 'REVENU MENSUEL'
UNION ALL
SELECT 35, 'en', 'EXCHANGE-TRADED FUND'
UNION ALL
SELECT 35, 'fr', 'FONDS NÉGOCIÉ EN BOURSE'
UNION ALL
SELECT 36, 'en', 'TRUST UNITS'
UNION ALL
SELECT 36, 'fr', 'PARTS DE FIDUCIE'
UNION ALL
SELECT 37, 'en', 'INSTALLMENT RECEIPT'
UNION ALL
SELECT 37, 'fr', 'REÇU DE VERSEMENT'
UNION ALL
SELECT 38, 'en', 'MUTUAL FUNDS'
UNION ALL
SELECT 38, 'fr', 'FONDS COMMUNS DE PLACEMENT'
UNION ALL
SELECT 39, 'en', 'SEGREGATED FUNDS'
UNION ALL
SELECT 39, 'fr', 'FONDS DISTINCTS'
UNION ALL
SELECT 40, 'en', 'MUTUAL FD – FIXED INC'
UNION ALL
SELECT 40, 'fr', 'FONDS COMM. – REV. FIXE'
UNION ALL
SELECT 41, 'en', 'MUTUAL FD – OTHER'
UNION ALL
SELECT 41, 'fr', 'FONDS COMM. – AUTRE'
UNION ALL
SELECT 42, 'en', 'MUTUAL FD – CASH/MONEY'
UNION ALL
SELECT 42, 'fr', 'FONDS COMM – LIQUIDITÉS/MARCHÉ MONÉTAIRE'
UNION ALL
SELECT 43, 'en', 'MUTUAL FD – EQUITY'
UNION ALL
SELECT 43, 'fr', 'FONDS COMM – ACTIONS'
UNION ALL
SELECT 44, 'en', 'MUTUAL FD – BALANCED'
UNION ALL
SELECT 44, 'fr', 'FONDS COMM – ÉQUILIBRÉ'
UNION ALL
SELECT 45, 'en', 'PREFERRED SHARES'
UNION ALL
SELECT 45, 'fr', 'ACTIONS PRIVILÉGIÉES'
UNION ALL
SELECT 46, 'en', 'LIMITED PARTNERSHIP'
UNION ALL
SELECT 46, 'fr', 'SOCIÉTÉ EN COMMANDITE'
UNION ALL
SELECT 47, 'en', 'RIGHTS/WARRANTS'
UNION ALL
SELECT 47, 'fr', 'DROITS/BONS DE SOUSC.'
UNION ALL
SELECT 48, 'en', 'UNITS'
UNION ALL
SELECT 48, 'fr', 'PARTS'
UNION ALL
SELECT 49, 'en', 'OPTIONS'
UNION ALL
SELECT 49, 'fr', 'OPTIONS'
UNION ALL
SELECT 50, 'en', 'OTHER INVESTMENTS'
UNION ALL
SELECT 50, 'fr', 'AUTRES PLACEMENTS'
UNION ALL
SELECT 51, 'en', 'MONEY MARKET'
UNION ALL
SELECT 51, 'fr', 'MARCHÉ MONÉTAIRE'
UNION ALL
SELECT 52, 'en', 'GIC’S'
UNION ALL
SELECT 52, 'fr', 'CPG'
UNION ALL
SELECT 53, 'en', 'CANADA SAVINGS BOND'
UNION ALL
SELECT 53, 'fr', 'OBLIG. D’ÉPARGNE DU CANADA'
UNION ALL
SELECT 54, 'en', 'PRIVATE COMPANIES'
UNION ALL
SELECT 54, 'fr', 'SOCIÉTÉS FERMÉES'
)

select subview.Label_id, subview.EN_DESC, subview.FR_DESC from 
(SELECT 
    t2.Label_id, 
    ISNULL(MAX(CASE WHEN t2.User_Language = 'en' THEN t2.Security_Class_Description END), '') AS EN_DESC,
    ISNULL(MAX(CASE WHEN t2.User_Language = 'fr' THEN t2.Security_Class_Description END), '') AS FR_DESC,
    ISNULL(t1.[descr],'') AS descr
FROM FCCDPX.dbo.mfsccl t1
RIGHT JOIN tempReportLegend t2 ON t1.[descr] = t2.Security_Class_Description
WHERE t1.[descr] is null
GROUP BY t2.Label_id, t1.[descr]) as subview


