--COMM_MTD_SUMMARY
	--renamed X_ATTRIB3 to DATE_ROW_ID

	--Change VARCHAR to Integer data tyoe
	ALTER TABLE [COMMWEB].[COMM_MTD_SUMMARY]  
	ALTER COLUMN [DATE_ROW_ID] INT

	--Create FK relationship to Calendar.ROW_ID
	ALTER TABLE [COMMWEB].[COMM_MTD_SUMMARY]
	ADD CONSTRAINT FK_COMM_MTD_SUMMARY_DATE_ROW_ID FOREIGN KEY ([DATE_ROW_ID])
	REFERENCES [RWL].[CALENDAR] ([ROW_ID]);

	--Run the following update
	update [TempDataLake].[COMMWEB].[COMM_MTD_SUMMARY]
	set [DATE_ROW_ID] =  CAST(YEAR([TRAN_PROCESS_DATE]) AS varchar(4)) + CAST(RIGHT(FORMAT(MONTH([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2)) + CAST(RIGHT(FORMAT(DAY([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2))
	FROM [TempDataLake].[COMMWEB].[COMM_MTD_SUMMARY];

--COMM_MTD_SUMMARY_HIST
	--renamed X_ATTRIB3 to DATE_ROW_ID

	--Change VARCHAR to Integer data tyoe
	ALTER TABLE [COMMWEB].[COMM_MTD_SUMMARY_HIST]  
	ALTER COLUMN [DATE_ROW_ID] INT

	--Create FK relationship to Calendar.ROW_ID
	ALTER TABLE [COMMWEB].[COMM_MTD_SUMMARY_HIST]
	ADD CONSTRAINT FK_COMM_MTD_SUMMARY_HIST_DATE_ROW_ID FOREIGN KEY ([DATE_ROW_ID])
	REFERENCES [RWL].[CALENDAR] ([ROW_ID]);

	----Run the following update
	update [TempDataLake].[COMMWEB].[COMM_MTD_SUMMARY_HIST]
	set [DATE_ROW_ID] =  CAST(YEAR([TRAN_PROCESS_DATE]) AS varchar(4)) + CAST(RIGHT(FORMAT(MONTH([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2)) + CAST(RIGHT(FORMAT(DAY([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2))
	FROM [TempDataLake].[COMMWEB].[COMM_MTD_SUMMARY_HIST];

--COMM_YTD_SUMMARY
	--renamed X_ATTRIB3 to DATE_ROW_ID

	--Change VARCHAR to Integer data tyoe
	ALTER TABLE [COMMWEB].[COMM_YTD_SUMMARY]  
	ALTER COLUMN [DATE_ROW_ID] INT

	--Create FK relationship to Calendar.ROW_ID
	ALTER TABLE [COMMWEB].[COMM_YTD_SUMMARY]
	ADD CONSTRAINT FK_COMM_YTD_SUMMARY_DATE_ROW_ID FOREIGN KEY ([DATE_ROW_ID])
	REFERENCES [RWL].[CALENDAR] ([ROW_ID]);

	----Run the following update
	update [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY]
	set [DATE_ROW_ID] =  CAST(YEAR([TRAN_PROCESS_DATE]) AS varchar(4)) + CAST(RIGHT(FORMAT(MONTH([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2)) + CAST(RIGHT(FORMAT(DAY([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2))
	FROM [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY];

--COMM_YTD_SUMMARY_HIST
	--renamed X_ATTRIB3 to DATE_ROW_ID

	--Change VARCHAR to Integer data tyoe
	ALTER TABLE [COMMWEB].[COMM_YTD_SUMMARY_HIST]  
	ALTER COLUMN [DATE_ROW_ID] INT

	--Create FK relationship to Calendar.ROW_ID
	ALTER TABLE [COMMWEB].[COMM_YTD_SUMMARY_HIST]
	ADD CONSTRAINT FK_COMM_YTD_SUMMARY_HIST_DATE_ROW_ID FOREIGN KEY ([DATE_ROW_ID])
	REFERENCES [RWL].[CALENDAR] ([ROW_ID]);

	----Run the following update
	update [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY_HIST]
	set [DATE_ROW_ID] =  CAST(YEAR([TRAN_PROCESS_DATE]) AS varchar(4)) + CAST(RIGHT(FORMAT(MONTH([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2)) + CAST(RIGHT(FORMAT(DAY([TRAN_PROCESS_DATE]), '00'), 2) AS varchar(2))
	FROM [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY_HIST];




--IA_ROW_ID updates
	--MTD SUmmary
UPDATE [COMMWEB].[COMM_MTD_SUMMARY] 
SET IA_ROW_ID = IC.ROW_ID
FROM [COMMWEB].[COMM_MTD_SUMMARY] AS DS  
INNER JOIN [COMMWEB].[COMM_IA_CODE] AS IC ON IC.IA_CODE = DS.IA_CODE;

	--MTD SUmmary HIST
UPDATE [COMMWEB].[COMM_MTD_SUMMARY_HIST] 
SET IA_ROW_ID = IC.ROW_ID
FROM [COMMWEB].[COMM_MTD_SUMMARY_HIST] AS DS  
INNER JOIN [COMMWEB].[COMM_IA_CODE] AS IC ON IC.IA_CODE = DS.IA_CODE;

	--YTD summary
UPDATE [COMMWEB].[COMM_YTD_SUMMARY] 
SET IA_ROW_ID = IC.ROW_ID
FROM [COMMWEB].[COMM_YTD_SUMMARY] AS DS  
INNER JOIN [COMMWEB].[COMM_IA_CODE] AS IC ON IC.IA_CODE = DS.IA_CODE;

	--YTD summary HIST
UPDATE [COMMWEB].[COMM_YTD_SUMMARY_HIST] 
SET IA_ROW_ID = IC.ROW_ID
FROM [COMMWEB].[COMM_YTD_SUMMARY_HIST] AS DS  
INNER JOIN [COMMWEB].[COMM_IA_CODE] AS IC ON IC.IA_CODE = DS.IA_CODE;

----------------------------------------------------------------------
----------------------------------------------------------------------
----removing PRIMARY KEY CONSTRAINT

--MTD HIST
-- Drop the existing primary key constraint
ALTER TABLE [TempDataLake].[COMMWEB].[COMM_MTD_SUMMARY_HIST]
DROP CONSTRAINT[PK_COMM_MTD_SUMMARY_HIST]

-- Create clustered index on TRAN_PROCESS_DATE and IA_CODE columns
CREATE CLUSTERED INDEX CIX_MTD_SUMMARY_HIST_TRAN_DATE_IA_CODE
ON [TempDataLake].[COMMWEB].[COMM_MTD_SUMMARY_HIST] (TRAN_PROCESS_DATE, IA_CODE);

-- Add a new primary key constraint using only ROW_ID
ALTER TABLE [TempDataLake].[COMMWEB].[COMM_MTD_SUMMARY_HIST]
ADD CONSTRAINT [PK_COMM_MTD_SUMMARY_HIST] PRIMARY KEY (ROW_ID);

--YTD summary
-- Drop the existing primary key constraint
ALTER TABLE [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY]
DROP CONSTRAINT[PK_COMM_YTD_SUMMARY]

-- Create clustered index on TRAN_PROCESS_DATE and IA_CODE columns
CREATE CLUSTERED INDEX CIX_YTD_SUMMARY_TRAN_DATE_IA_CODE
ON [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY] (TRAN_PROCESS_DATE, IA_CODE);

-- Add a new primary key constraint using only ROW_ID
ALTER TABLE [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY]
ADD CONSTRAINT [PK_COMM_YTD_SUMMARY] PRIMARY KEY (ROW_ID);

--YTD HIST
-- Drop the existing primary key constraint
ALTER TABLE [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY_HIST]
DROP CONSTRAINT[PK_COMM_YTD_SUMMARY_HIST_v2]

-- Create clustered index on TRAN_PROCESS_DATE and IA_CODE columns
CREATE CLUSTERED INDEX CIX_YTD_SUMMARY_HIST_TRAN_DATE_IA_CODE
ON [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY_HIST] (TRAN_PROCESS_DATE, IA_CODE);

-- Add a new primary key constraint using only ROW_ID
ALTER TABLE [TempDataLake].[COMMWEB].[COMM_YTD_SUMMARY_HIST]   --note constraint was called [PK_COMM_YTD_SUMMARY_HIST_v2]
ADD CONSTRAINT [PK_COMM_YTD_SUMMARY_HIST] PRIMARY KEY (ROW_ID);


